### ISSUE TITLE
Use https URL on README

### ISSUE THREAD

**Issue by ghost** [kleber-swf/orchis-dark-ulauncher#1]
You have it set to use the SSH URL, however this requires authentication. In other words, only the repo. owner or those authorized can clone the repo. if you use the SSH URL. Please change it to the https one: `https://github.com/kleber-swf/orchis-dark-ulauncher.git`.

**Comment by RedBearAK** [comment]
@kleber-swf 

Yes, please fix the URL, it doesn't work. I had to download, make a folder and install the files manually. 

```
git clone git@github.com:kleber-swf/orchis-dark-ulauncher.git \
  ~/.config/ulauncher/user-themes/orchis-dark
Cloning into '/home/kris/.config/ulauncher/user-themes/orchis-dark'...
Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kleber-swf** [comment]
Thnaks for the heads up!
